//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartID { get; set; }
        public string PartName { get; set; }
        public decimal Price { get; set; }
        public int SupplierID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Order Order { get; set; }
    }
}
